title: "Seminar on Advanced Topics in Theoretical Neuroscience"
theme: jekyll-theme-slate
description: "Center for Theoretical Neuroscience - Zuckerman Institute, Columbia University"
github:
is_project_page: true
