title: "Seminar on Advanced Topics in Theoretical Neuroscience - Columbia University 2019"
theme: jekyll-theme-minimal
description: "Center for Theoretical Neuroscience - ZI, Columbia University"
github:
is_project_page: true
